FROM nginx:1

# upgrade
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends python-pip curl && \
    rm -rf /var/lib/apt/lists/* && \
    pip install envtpl

# nginx
ADD docker/nginx.conf.tpl /etc/nginx/nginx.conf.tpl

# run script
ADD docker/run.sh ./run.sh

# kopf
ADD . /kopf

# logs
VOLUME ["/var/log/nginx"]

# ports
EXPOSE 80 443

ENTRYPOINT ["/run.sh"]
